server.port=8083
spring.application.name=notification-service

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Mail Config (Placeholder)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true