# Application Name
spring.application.name=auth-service

# Database Connection (Matches your Docker Compose)
spring.datasource.url=jdbc:postgresql://localhost:5432/badmintoz_auth
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
# "update" automatically creates tables based on your Java classes (Good for Dev, BAD for Prod)
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries in the console so we can debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Use PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Force Eureka to use IP/Localhost instead of the computer name
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost